### ISSUE TITLE
hevc_HM

### ISSUE THREAD

**Issue by zrybeauty** [Goluck-Konuko/hdac#1]
The folder "modules\utils\hevc_hm" is empty. And some error happened as “FileNotFoundError: [Errno 2] No such file or directory: 'modules/utils/hevc_hm/config_template.cfg'” when I python run.py.

Do I need to download HM project from official web and add it to "modules\utils\hevc_hm"?

Looking forward to your reply ^_^

**Comment by Goluck-Konuko** [comment]
Hi, yes you do need the HM model and the folder was too large to include with the other files on github. Here is the a link to download it from my gdrive <<https://drive.google.com/drive/folders/1SRppJoipBX8-tODl9tcSGl6nAybfkbMT?usp=share_link>>
