### ISSUE TITLE
intraPeriod

### ISSUE THREAD

**Issue by melissa-allouche** [Goluck-Konuko/hdac#2]
There seems to be an error when running the repository. We are getting intraPeriod as a value for the config attribute of IntraPeriod instead of an actual number which is interfering with HEVC. 

<img width="1263" alt="Screen Shot 2023-03-05 at 8 28 38 PM" src="https://user-images.githubusercontent.com/88145245/222978835-d28cff23-bb4b-4883-b09c-d1a31965727c.png">

**Comment by Goluck-Konuko** [comment]
Hi, I've updated the HEVC class to update the intraPeriod value on the config template.
